environment:
  matrix:

    - JOB: "3.6 64-bit"
      PYTHON_HOME: "C:\\Python36-x64"

    - JOB: "3.7 64-bit"
      PYTHON_HOME: "C:\\Python37-x64"

skip_branch_with_pr: true

matrix:
  fast_finish: true

install:
  # Prepend Python to the PATH of this build
  - "SET PATH=%PYTHON_HOME%;%PYTHON_HOME%\\Scripts;%PATH%"

  # check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # upgrade pip to avoid out-of-date warnings
  - "python -m pip install --disable-pip-version-check --user --upgrade pip"
  - "python -m pip --version"

  # install the dependencies to run the tests
  - "python -m pip install -r dev-requirements.txt"


build: false

test_script:
  - "tox -e py"
